ALTER TABLE chat_messages ADD COLUMN cost_usd REAL NOT NULL DEFAULT 0;
ALTER TABLE chat_messages ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chat_messages ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
