import { useState, useEffect, useCallback } from 'react';
import { ImageIcon, Search, Download, Trash2, ExternalLink, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { mediaApi } from '../lib/api-helpers';
import type { MediaItem, MediaListResponse } from '../lib/types';
import { EmptyState } from '../components/EmptyState';
import { Header } from '../components/Header';
import { Modal } from '../components/Modal';
import { Button } from '../components/Button';
import { LoadingSpinner } from '../components/LoadingSpinner';
import { useToast } from '../components/Toast';

const typeFilters = ['all', 'image', 'audio', 'video'] as const;
const sourceFilters = ['all', 'fal', 'dalle', 'upload'] as const;

const sourceLabels: Record<string, string> = {
  all: 'All',
  fal: 'FAL',
  dalle: 'DALL-E',
  upload: 'Upload',
  tool: 'Tool',
};

const sourceBadgeColors: Record<string, string> = {
  fal: 'bg-purple-500/20 text-purple-300',
  dalle: 'bg-green-500/20 text-green-300',
  upload: 'bg-blue-500/20 text-blue-300',
  tool: 'bg-amber-500/20 text-amber-300',
};

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

const PER_PAGE = 24;

export function MediaLibrary() {
  const { toast } = useToast();

  const [items, setItems] = useState<MediaItem[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);

  const [typeFilter, setTypeFilter] = useState<string>('all');
  const [sourceFilter, setSourceFilter] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [sortNewest, setSortNewest] = useState(true);

  const [selectedItem, setSelectedItem] = useState<MediaItem | null>(null);
  const [deleting, setDeleting] = useState(false);

  const fetchMedia = useCallback(async () => {
    setLoading(true);
    try {
      let result: MediaListResponse;
      if (searchQuery.trim()) {
        result = await mediaApi.search(searchQuery.trim(), page);
      } else {
        result = await mediaApi.list({
          page,
          per_page: PER_PAGE,
          type: typeFilter !== 'all' ? typeFilter : undefined,
          source: sourceFilter !== 'all' ? sourceFilter : undefined,
        });
      }
      let sorted = result.items ?? [];
      if (!sortNewest) {
        sorted = [...sorted].reverse();
      }
      setItems(sorted);
      setTotal(result.total ?? 0);
    } catch {
      toast('error', 'Failed to load media');
    } finally {
      setLoading(false);
    }
  }, [page, typeFilter, sourceFilter, searchQuery, sortNewest, toast]);

  useEffect(() => {
    fetchMedia();
  }, [fetchMedia]);

  // Reset page when filters change
  useEffect(() => {
    setPage(1);
  }, [typeFilter, sourceFilter, searchQuery]);

  const totalPages = Math.max(1, Math.ceil(total / PER_PAGE));

  const handleDelete = async (item: MediaItem) => {
    setDeleting(true);
    try {
      await mediaApi.delete(item.id);
      setItems((prev) => prev.filter((i) => i.id !== item.id));
      setTotal((prev) => prev - 1);
      setSelectedItem(null);
      toast('success', 'Media deleted');
    } catch {
      toast('error', 'Failed to delete media');
    } finally {
      setDeleting(false);
    }
  };

  if (loading && items.length === 0) {
    return (
      <div className="flex flex-col h-full">
        <Header title="Media Library" />
        <div className="flex-1 flex items-center justify-center">
          <LoadingSpinner message="Loading media..." />
        </div>
      </div>
    );
  }

  if (!loading && items.length === 0 && !searchQuery && typeFilter === 'all' && sourceFilter === 'all') {
    return (
      <div className="flex flex-col h-full">
        <Header title="Media Library" />
        <div className="flex-1 flex items-center justify-center">
          <EmptyState
            icon={<ImageIcon className="w-8 h-8" />}
            title="No Media Yet"
            description="Media generated by agents will appear here."
          />
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      <Header title="Media Library" count={total} />

      {/* Filter bar */}
      <div className="flex flex-wrap items-center gap-3 px-4 md:px-6 py-3 border-b border-border-0 bg-surface-0">
        {/* Type pills */}
        <div className="flex items-center gap-1">
          {typeFilters.map((t) => (
            <button
              key={t}
              onClick={() => setTypeFilter(t)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer ${
                typeFilter === t
                  ? 'bg-accent-muted text-accent-text'
                  : 'text-text-2 hover:text-text-1 hover:bg-surface-2'
              }`}
            >
              {t === 'all' ? 'All' : t.charAt(0).toUpperCase() + t.slice(1) + 's'}
            </button>
          ))}
        </div>

        <div className="w-px h-5 bg-border-0 hidden sm:block" />

        {/* Source pills */}
        <div className="flex items-center gap-1">
          {sourceFilters.map((s) => (
            <button
              key={s}
              onClick={() => setSourceFilter(s)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer ${
                sourceFilter === s
                  ? 'bg-accent-muted text-accent-text'
                  : 'text-text-2 hover:text-text-1 hover:bg-surface-2'
              }`}
            >
              {sourceLabels[s]}
            </button>
          ))}
        </div>

        <div className="flex-1" />

        {/* Search */}
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-text-3" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search prompts..."
            className="pl-8 pr-3 py-1.5 rounded-lg bg-surface-2 border border-border-0 text-text-1 text-xs placeholder:text-text-3 focus:outline-none focus:ring-2 focus:ring-accent-primary w-48"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-text-3 hover:text-text-1 cursor-pointer"
            >
              <X className="w-3 h-3" />
            </button>
          )}
        </div>

        {/* Sort toggle */}
        <button
          onClick={() => setSortNewest(!sortNewest)}
          className="px-3 py-1.5 rounded-lg text-xs font-medium text-text-2 hover:text-text-1 hover:bg-surface-2 transition-colors cursor-pointer"
        >
          {sortNewest ? 'Newest' : 'Oldest'}
        </button>
      </div>

      {/* Grid */}
      <div className="flex-1 overflow-y-auto p-4 md:p-6">
        {loading ? (
          <div className="flex items-center justify-center py-12">
            <LoadingSpinner message="Loading..." />
          </div>
        ) : items.length === 0 ? (
          <div className="flex items-center justify-center py-12">
            <p className="text-sm text-text-3">No media matches your filters.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {items.map((item) => (
              <button
                key={item.id}
                onClick={() => setSelectedItem(item)}
                className="group bg-surface-1 rounded-lg border border-border-0 overflow-hidden hover:border-border-1 transition-colors text-left cursor-pointer"
              >
                {/* Thumbnail */}
                <div className="relative aspect-square bg-surface-2 overflow-hidden">
                  {item.media_type === 'image' ? (
                    <img
                      src={mediaApi.fileUrl(item.id)}
                      alt={item.prompt || item.filename}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-200"
                      loading="lazy"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <ImageIcon className="w-12 h-12 text-text-3" />
                    </div>
                  )}
                  {/* Source badge */}
                  <span
                    className={`absolute top-2 right-2 px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                      sourceBadgeColors[item.source] ?? 'bg-surface-2 text-text-2'
                    }`}
                  >
                    {sourceLabels[item.source] ?? item.source}
                  </span>
                </div>
                {/* Info */}
                <div className="p-3">
                  <p className="text-sm text-text-1 truncate">
                    {item.prompt || item.filename}
                  </p>
                  <p className="text-xs text-text-3 mt-1">
                    {formatDate(item.created_at)}
                  </p>
                </div>
              </button>
            ))}
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex items-center justify-center gap-3 pt-6 pb-2">
            <Button
              variant="ghost"
              size="sm"
              disabled={page <= 1}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              icon={<ChevronLeft className="w-4 h-4" />}
            >
              Prev
            </Button>
            <span className="text-xs text-text-3 tabular-nums">
              Page {page} of {totalPages}
            </span>
            <Button
              variant="ghost"
              size="sm"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              icon={<ChevronRight className="w-4 h-4" />}
            >
              Next
            </Button>
          </div>
        )}
      </div>

      {/* Detail modal */}
      {selectedItem && (
        <Modal
          open={!!selectedItem}
          onClose={() => setSelectedItem(null)}
          title="Media Detail"
          size="lg"
        >
          <div className="flex flex-col md:flex-row gap-6">
            {/* Image */}
            <div className="flex-1 min-w-0">
              {selectedItem.media_type === 'image' ? (
                <img
                  src={mediaApi.fileUrl(selectedItem.id)}
                  alt={selectedItem.prompt || selectedItem.filename}
                  className="w-full rounded-lg border border-border-0"
                />
              ) : (
                <div className="w-full aspect-square rounded-lg bg-surface-2 flex items-center justify-center">
                  <ImageIcon className="w-16 h-16 text-text-3" />
                </div>
              )}
            </div>

            {/* Metadata */}
            <div className="w-full md:w-64 flex-shrink-0 space-y-4">
              {selectedItem.prompt && (
                <div>
                  <label className="block text-xs font-semibold text-text-3 uppercase tracking-wider mb-1">Prompt</label>
                  <p className="text-sm text-text-1 whitespace-pre-wrap">{selectedItem.prompt}</p>
                </div>
              )}

              <div className="space-y-2 text-xs">
                {selectedItem.source_model && (
                  <div className="flex justify-between">
                    <span className="text-text-3">Model</span>
                    <span className="text-text-1">{selectedItem.source_model}</span>
                  </div>
                )}
                {(selectedItem.width > 0 || selectedItem.height > 0) && (
                  <div className="flex justify-between">
                    <span className="text-text-3">Dimensions</span>
                    <span className="text-text-1">{selectedItem.width}x{selectedItem.height}</span>
                  </div>
                )}
                {selectedItem.size_bytes > 0 && (
                  <div className="flex justify-between">
                    <span className="text-text-3">Size</span>
                    <span className="text-text-1">{formatBytes(selectedItem.size_bytes)}</span>
                  </div>
                )}
                <div className="flex justify-between">
                  <span className="text-text-3">Source</span>
                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-semibold ${sourceBadgeColors[selectedItem.source] ?? 'bg-surface-2 text-text-2'}`}>
                    {sourceLabels[selectedItem.source] ?? selectedItem.source}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-3">Created</span>
                  <span className="text-text-1">{formatDate(selectedItem.created_at)}</span>
                </div>
              </div>

              {selectedItem.thread_id && (
                <a
                  href={`/chat/${selectedItem.thread_id}`}
                  className="flex items-center gap-1.5 text-xs text-accent-text hover:underline"
                >
                  <ExternalLink className="w-3 h-3" />
                  View Thread
                </a>
              )}

              <div className="flex gap-2 pt-2">
                <a
                  href={mediaApi.fileUrl(selectedItem.id)}
                  download={selectedItem.filename}
                  className="flex-1"
                >
                  <Button variant="ghost" size="sm" icon={<Download className="w-4 h-4" />} className="w-full">
                    Download
                  </Button>
                </a>
                <Button
                  variant="ghost"
                  size="sm"
                  icon={<Trash2 className="w-4 h-4" />}
                  onClick={() => handleDelete(selectedItem)}
                  disabled={deleting}
                  className="text-red-400 hover:text-red-300"
                >
                  {deleting ? 'Deleting...' : 'Delete'}
                </Button>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}
